// <auto-generated />
namespace ProjectDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MigValid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigValid));
        
        string IMigrationMetadata.Id
        {
            get { return "201910310634432_MigValid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
